backbone: se_resnext50_32x4d
exp_name: original
description: set min epoch = 70, use early stopping, use a2 augmentation
# data_folder: /data/lxd/datasets/2022-03-02-Eggs
data_folder: /data2/lxd/datasets/2022-04-18-Eggs
training_set: train.csv
test_set : test.csv
# these test set are sampled by the real-world distribution
test_real_world_set: seed
test_real_world_num: 1
num_classes: 8
lr: 0.001
# training 
train_transforms: a2
train_batch_size: 8
fold_i: 0
val_batch_size: 32
anchor_batch_size: 6
save_top_k: 5
training_mode: ddp
num_workers: 8
image_size: [700, 600]
seed: 2022
min_epochs: 20
max_epochs: 70
patience: 20
gpus: [0,1]
precision: 16
gradient_clip_val: 0
soft_labels_filename: ""
log_dir: logs_submit
sample_num: 6
debug: false
clean_debug: true
# normalization:
#   mean: [0.4914, 0.4822, 0.4465]
#   std: [0.247, 0.243, 0.261]
norm: 
  mean: [
    0.29655125737190247,
    0.09730149805545807,
    0.06337454915046692
  ]
  std: [
    0.3412066698074341,
    0.24394549429416656,
    0.21203480660915375
  ]
resume_from_checkpoint: /data2/lxd/project/cvpr2020-plant-pathology/logs_submit/20220420-1135-original/checkpoints
checkpoints: 